/**
 * WARNING: This is a generated file. Do not modify.
 *
 * Source: buildscripts/idl/idlc.py --include src --base_dir build/opt --target_arch x86_64 --header build/opt/mongo/embedded/mongo_embedded/mongo_embedded_test_gen.h --output build/opt/mongo/embedded/mongo_embedded/mongo_embedded_test_gen.cpp src/mongo/embedded/mongo_embedded/mongo_embedded_test.idl
 */

#include "mongo/platform/basic.h"

#include "mongo/embedded/mongo_embedded/mongo_embedded_test_gen.h"

#include <bitset>
#include <set>

#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/auth/authorization_contract.h"
#include "mongo/db/commands.h"
#include "mongo/idl/command_generic_argument.h"
#include "mongo/util/options_parser/option_section.h"
#include "mongo/util/options_parser/startup_option_init.h"
#include "mongo/util/options_parser/startup_options.h"

namespace mongo {
namespace embedded {


Status addMongoEmbeddedTestOptions(optionenvironment::OptionSection* options_ptr) {
    auto& options = *options_ptr;
    namespace moe = ::mongo::optionenvironment;

    options
        .addOptionChaining("tempPath", "tempPath", moe::String, "Directory to place mongo::TempDir subdirectories", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceCommandLine)
    ;

    return Status::OK();
}

}  // namespace embedded
}  // namespace mongo
