/**
 * WARNING: This is a generated file. Do not modify.
 *
 * Source: buildscripts/idl/idlc.py --include src --base_dir build/opt --target_arch x86_64 --header build/opt/mongo/unittest/integration_test_main_gen.h --output build/opt/mongo/unittest/integration_test_main_gen.cpp src/mongo/unittest/integration_test_main.idl
 */

#include "mongo/platform/basic.h"

#include "mongo/unittest/integration_test_main_gen.h"

#include <bitset>
#include <set>

#include "mongo/bson/bsonobjbuilder.h"
#include "mongo/db/auth/authorization_contract.h"
#include "mongo/db/commands.h"
#include "mongo/idl/command_generic_argument.h"
#include "mongo/util/options_parser/option_section.h"
#include "mongo/util/options_parser/startup_option_init.h"
#include "mongo/util/options_parser/startup_options.h"

namespace mongo {
namespace unittest {


namespace  {
MONGO_MODULE_STARTUP_OPTIONS_REGISTER(idl_defff4f72d2ec1d382cfa9727d16b090a435227f)(InitializerContext*) {
    auto& options = optionenvironment::startupOptions;
    namespace moe = ::mongo::optionenvironment;

    options
        .addOptionChaining("help", "help", moe::Switch, "Display help", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceCommandLine)
    ;

    options
        .addOptionChaining("connectionString", "connectionString", moe::String, "The connection string associated with the test fixture that this integration test should run against.", {}, {}, moe::OptionSection::OptionParserUsageType::IDLAutoGeneratedCode)
        .setSources(moe::SourceCommandLine)
        .setDefault(moe::Value("localhost:27017"))
    ;

}
}  // namespace 

}  // namespace unittest
}  // namespace mongo
